# Generated by Django 3.1.5 on 2021-02-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(default=None, max_length=20, null=True, unique=True, verbose_name='phone'),
        ),
    ]
