# Generated by Django 3.1.5 on 2021-03-28 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=16, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='products',
            name='request',
            field=models.CharField(max_length=200, null=True, verbose_name='request'),
        ),
    ]
