# Generated by Django 3.1.5 on 2021-03-28 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210328_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=6, max_digits=16, null=True, verbose_name='price'),
        ),
    ]
