# Generated by Django 3.1.5 on 2021-02-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210203_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='token',
            field=models.CharField(default=None, max_length=255, null=True, unique=True, verbose_name='token'),
        ),
    ]
