# Generated by Django 3.1.5 on 2021-02-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_profile_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoring',
            name='id_user',
            field=models.IntegerField(verbose_name='id user'),
        ),
        migrations.AlterField(
            model_name='monitoring',
            name='sku',
            field=models.IntegerField(verbose_name='sku'),
        ),
    ]
