# Generated by Django 3.1.5 on 2021-03-29 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210328_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='brand',
            field=models.CharField(max_length=200, null=True, verbose_name='brand'),
        ),
        migrations.AlterField(
            model_name='products',
            name='categorie',
            field=models.CharField(max_length=200, null=True, verbose_name='categorie'),
        ),
        migrations.AlterField(
            model_name='products',
            name='color',
            field=models.CharField(max_length=200, null=True, verbose_name='color'),
        ),
    ]
